### PR TITLE
Fix SYMVER to be built using attributes for GCC 13.2

### LINKED ISSUE #136: symver test fails to build
Consider updating the test in https://github.com/LLNL/GOTCHA/tree/develop/test/symver as it fails to build with newer versions of GCC

```
cd /builddir/build/BUILD/GOTCHA-1.0.5/redhat-linux-build/test/symver && /usr/bin/cmake -E cmake_link_script CMakeFiles/retX.dir/link.txt --verbose=1
/usr/bin/gcc -fPIC -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Werror=implicit-function-declaration -Werror=implicit-int -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wl,--version-script=/builddir/build/BUILD/GOTCHA-1.0.5/test/symver/symver.map -shared -Wl,-soname,libretX.so -o libretX.so CMakeFiles/retX.dir/retX_old.c.o CMakeFiles/retX.dir/retX_new.c.o 
/builddir/build/BUILD/GOTCHA-1.0.5/src/gotcha_auxv.c: In function ‘get_vdso_from_auxv’:
/builddir/build/BUILD/GOTCHA-1.0.5/src/gotcha_auxv.c:108:21: warning: ‘vdso_dynamic’ may be used uninitialized [-Wmaybe-uninitialized]
  108 |       if (m->l_addr + vdso_dynamic == (ElfW(Addr))m->l_ld) {
      |           ~~~~~~~~~~^~~~~~~~~~~~~~
/builddir/build/BUILD/GOTCHA-1.0.5/src/gotcha_auxv.c:93:14: note: ‘vdso_dynamic’ was declared here
   93 |   ElfW(Addr) vdso_dynamic;
      |              ^~~~~~~~~~~~
gmake[2]: Leaving directory '/builddir/build/BUILD/GOTCHA-1.0.5/redhat-linux-build'
[ 22%] Built target num3
{standard input}: Assembler messages:
{standard input}: Error: invalid attempt to declare external version name as default in symbol `retX@@GOTCHA_2'
```
Full log https://kojipkgs.fedoraproject.org//work/tasks/3462/109123462/build.log

### PR DESCRIPTION
**Pull request by hariharan-devarajan**
Fixes #136

### CODE REVIEW

**Comment by hariharan-devarajan** [comment]
@bkmgit I tried compiling with gcc 1.13.2 on ubuntu with #139. It seems to be building and running. Can you confirm if this PR solves your issue?

**Comment by bertwesarg** [comment]
"gcc 1.13.2"?

**Comment by bkmgit** [comment]
Tried on Fedora 39 with
```
sudo -y dnf install check-devel cmake git gcc-c++ python3-sphinx
git clone https://github.com/LLNL/GOTCHA
cd GOTCHA
git checkout build/fix_symver_gcc13
sed -i 's/-O0 //g' test/hammer/CMakeLists.txt
export CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Werror=implicit-function-declaration -Werror=implicit-int -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
export CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer '
mkdir build
cd build
cmake -DGOTCHA_ENABLE_TESTS=ON -DDEPENDENCIES_PREINSTALLED=TRUE ..
make
```
This fails with

```
[ 93%] Linking C shared library libretX.so
/usr/bin/ld: libretX.so: version node not found for symbol retX @ @GOTCHA_2
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [test/symver/CMakeFiles/retX.dir/build.make:113: test/symver/libretX.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1510: test/symver/CMakeFiles/retX.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

If it would help, can make a pull request to add a GitHub actions build on Fedora using a container.  Build flags are those used when packaging the library.  Without those flags for a hardened build, the build completes and tests pass.

**Comment by hariharan-devarajan** [comment]
> "gcc 1.13.2"?

Yes I installed that with spack and was able to compile with the above fixes. 

@bkmgit I will try it on a container with fedora. Which image of fedora are u using? Is it on Dockerhub?

**Comment by bertwesarg** [comment]
My point is, that "GCC 1.13.2" is probably a typo. If anything, that version was released in the 1980s.

**Comment by hariharan-devarajan** [comment]
> My point is, that "GCC 1.13.2" is probably a typo. If anything, that version was released in the 1980s.

Ah yes. I meant 13.2. Fixed the PR name too.

**Comment by bkmgit** [comment]
Created a pull request that uses GitHub Actions:
https://github.com/LLNL/GOTCHA/pull/141

The `O0` optimization flag in
https://github.com/LLNL/GOTCHA/blob/develop/test/hammer/CMakeLists.txt#L17
causes a build failure. Not sure why. Have removed it using sed, but maybe it can be fixed?

It does not have the other hardened build compiler flags which cause the build failure, can add these afterwards.

Finally, Fedora offers a CI service [packit](https://packit.dev/) - can add this as well as a follow on.

**Comment by hariharan-devarajan** [comment]
@mplegendre Do you know if the -O0 flag was added to that test?

**Comment by mplegendre** [comment]
I don't know.

File: test/symver/retX_new.c [hunk 1]
```diff
@@ -12,9 +12,6 @@ for more details.  You should have received a copy of the GNU Lesser General
...
 */
-
-int retX_new(int x) { return x; }
-__asm__(
-    "\t.globl  __retX_new\n"
-    "\t.equiv  __retX_new,retX_new\n"
-    "\t.symver __retX_new,retX@@GOTCHA_2");
+#include "sym_macro.h"
+SYMVER_ATTRIBUTE(retX_new, retX @ @GOTCHA_2)
+int retX_new(int x) { return x; }
```
Comment (bertwesarg) [inline test/symver/retX_new.c:17]: missing newline

Comment (hariharan-devarajan) [reply test/symver/retX_new.c]: Fixed

File: test/symver/retX_new.c [hunk 2]
```diff
@@ -12,9 +12,6 @@ for more details.  You should have received a copy of the GNU Lesser General
...
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
-
-int retX_new(int x) { return x; }
-__asm__(
-    "\t.globl  __retX_new\n"
-    "\t.equiv  __retX_new,retX_new\n"
-    "\t.symver __retX_new,retX@@GOTCHA_2");
+#include "sym_macro.h"
+SYMVER_ATTRIBUTE(retX_new, retX @ @GOTCHA_2)
```
Comment (bertwesarg) [inline test/symver/retX_new.c:16]: these spaces in `retX @ @GOTCHA_2` (instead of `retX@@GOTCHA_2`) are preserved by the preprocessor. I surprised, that the assembler removes them and produces the correct `retX@@GOTCHA_2`.

**Review by bertwesarg — APPROVED** [review]

File: test/symver/retX_new.c (hunk 2 above)
Comment (hariharan-devarajan) [reply test/symver/retX_new.c]: The clang formatting was creating the issue. I fixed the formatting.
