### PR TITLE
fix dlsym issue for glibc >= 2.34

### LINKED ISSUE #100: Build fails starting with glibc v2.34
As of version 2.34 of glibc (which is the latest as of Oct 2021), GOTCHA fails to build.  The problem is that GOTCHA uses `_dl_sym` and in v2.34, this is no longer exported.

### PR DESCRIPTION
**Pull request by hariharan-devarajan**
We get a compilation issue for newer kernels that use glibc >= 2.34 as _dl_sym is not exported. Fixes #100 

Re-Implement the logic of _dl_sym
 1. find the caller library using the program headers.
 2. find the first library which has the symbol for RTLD_DEFAULT
 3. find the second library which has the symbol for RTLD_NEXT

### CODE REVIEW

File: src/gotcha_dl.c [hunk 1]
```diff
@@ -5,7 +5,124 @@
...
+    dl_iterate_phdr(lib_header_callback, &addrs);
+
+    struct link_map *lib_iter;
+    int found_caller = 0;
+    int found_sym = 0;
+    for (lib_iter = _r_debug.r_map; lib_iter != 0; lib_iter = lib_iter->l_next) {
+        /* find the library of the caller */
+        if (lib_iter->l_addr == addrs.library_laddr)
+            found_caller = 1;
+        if (found_caller) {
```
Comment (mplegendre) [inline src/gotcha_dl.c:106]: This will search the caller library for the target symbol. We need start the search on the subsequent library in the link_map, not the caller library.

File: src/gotcha_dl.c [hunk 2]
```diff
@@ -5,7 +5,124 @@
...
+ * 1. find the caller library using the program headers.
+ * 2. find the first library which has the symbol for RTLD_DEFAULT
+ * 3. find the second library which has the symbol for RTLD_NEXT
+ * @param handle, handle for dl operation
+ * @param name, name of the symbol
+ * @param who, the virtual address of the caller
+ * @return symbol pointer
+ */
+
+static void * _dl_sym(void *handle, const char *name, void *who) {
```
Comment (mplegendre) [inline src/gotcha_dl.c:90]: Let's not treat this as a _dl_sym() replacement. We've reproduced some of the functionality of _dl_sym(RTLD_NEXT, ...), but not all of _dl_sym(). There's going to be cases where this _dl_sym() does the wrong thing, such as IFUNCs, library namespaces, and probably others. 

Instead we should use this new functionality to just replace the library identification part of dlsym(RTLD_NEXT, ...), which gotcha breaks. But we should try to use glib's dlsym() implementation for everything else. So I'd picture the pseudo-code in dlsym_wrapper() that calls this as something like:

```
if called with RTLD_NEXT:
  lib = gotchas_dlsym_rtld_next_lookup() 
  //There may be some more details here in mapping between a 'struct link_map' and the 
  // handle that's passed to dlsym(). I don't remember if dlsym's implementation can take 
  // a link_map pointer.
  return original_dlsym(lib, symbol_name) 
else:
  return original_dlsym(lib, symbol_name)
endif
```

File: test/dlopen/test_dlopen.c [hunk 3]
```diff
@@ -17,6 +17,8 @@ Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 #include <stdio.h>
 #include "gotcha/gotcha.h"
 
+# define RTLD_NEXT	((void *) -1l)
+# define RTLD_DEFAULT	((void *) 0)
```
Comment (mplegendre) [inline test/dlopen/test_dlopen.c:21]: We shouldn't have to redefine these. They should come from including dlfcn.h

File: src/gotcha_dl.c [hunk 4]
```diff
@@ -5,7 +5,124 @@
...
+    return 0;
+}
+/**
+ * This function looks for all symbols defined in rela or rel.
+ *
+ * @param name, symbol name
+ * @param lmap, library where we search for symbol.
+ * @return symbol pointer
+ */
+int dl_lookup_symbol_x(const char *name, struct link_map *lmap, void** symbol) {
```
Comment (mplegendre) [inline src/gotcha_dl.c:47]: Few things here. First, there's some code in gotcha.c in the prepare_symbol() function that almost does what you need. That code iterates over every link map, checks if a symbol name is exported, then makes a certain call on any matching symbol. I'd suggest refactoring that code so it can server both prepare_symbol() and this use case (you won't want to iterate over ever link map, and you don't want the setInternalBindingAddressPointer call on the symbol, but the rest is a match).

What the below code is doing is a linear iteration over both exported symbol and imported symbols. That's going to get incorrect matches when it hits the imported symbols. Also, for fast look up of exported symbols there is a hash map in the binary (try googling 'elf hash' and/or 'gnu elf hash' for details).  That's what the prepare_symbols() code uses.

And if you ever do need to legitimately write code like the below, there is a FOR_EACH_PLTREL macro in elf_ops.h, which you can use to avoid writing duplicate code for both rel and rela.

File: test/dlopen/test_dlopen.c [hunk 5]
```diff
@@ -82,6 +84,18 @@ int main()
...
+    if (test_retfive != NULL) {
+        fprintf(stderr, "ERROR: call to return_five should not be found in RTLD_NEXT\n");
+        had_error = -1;
+    }
+    /* Test 4: Does the dlsym implementation find the first occurrence of the symbol */
+    test_retfive = (int (*)(void)) dlsym(RTLD_DEFAULT, "return_five");
+    if (test_retfive == NULL || test_retfive() !=5) {
+        fprintf(stderr, "ERROR: call to return_five should be found in RTLD_DEFAULT\n");
+        had_error = -1;
+    }
```
Comment (mplegendre) [inline test/dlopen/test_dlopen.c:98]: We need a more substantive test case, one where there's multiple symbols that RTLD_NEXT could return, and we know that our RTLD_NEXT re-implementation is doing the right thing. I've already written that, let me find it and email it.

**Review by mplegendre — CHANGES_REQUESTED** [review]

File: src/gotcha_dl.c [hunk 6]
```diff
@@ -5,7 +5,124 @@
 #include "elf_ops.h"
 #include <dlfcn.h>
 
+#if defined(__GLIBC__) && __GLIBC__ >= 2 && __GLIBC_MINOR__ < 34
```
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: ok i named my function as gotchas_dlsym_rtld_next_lookup

File: src/gotcha_dl.c [hunk 7]
```diff
@@ -5,7 +5,124 @@
...
+    ElfW(Addr) end_addr = 0;
+    for (int i=0;i<info->dlpi_phnum;++i) {
+        ElfW(Addr) size = info->dlpi_phdr[i].p_vaddr + info->dlpi_phdr[i].p_memsz;
+        if (end_addr < size) end_addr = size;
+    }
+    ElfW(Addr) base_addr = info->dlpi_addr;
+    ElfW(Addr) end_phdr = base_addr + end_addr;
+    if (base_addr <= addrs->lookup_addr && end_phdr >= addrs->lookup_addr)
+        addrs->library_laddr = base_addr;
+    return 0;
```
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c:53]: Ok i fixed the logic to look at ranges of start and end.

File: src/gotcha_dl.c [hunk 8]
```diff
@@ -5,7 +5,124 @@
...
+    struct Addrs addrs;
+    addrs.lookup_addr = caller;
+    dl_iterate_phdr(lib_header_callback, &addrs);
+
+    struct link_map *lib_iter;
+    int found_caller = 0;
+    int found_sym = 0;
+    for (lib_iter = _r_debug.r_map; lib_iter != 0; lib_iter = lib_iter->l_next) {
+        /* find the library of the caller */
+        if (lib_iter->l_addr == addrs.library_laddr)
```
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: the ```dl_phdr_info``` does not contain the lmap or give any pointer to lmap. So I used the name to match the corresponding lmap.

File: src/gotcha_dl.c (hunk 1 above)
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: So we need two functions right?
1. for RTLD_DEFAULT, we should find the immediate library which has symbol. 
2. for RTLD_NEXT, its next of next. 

I fixed the logic to search symbol from next of lmap.

File: test/dlopen/test_dlopen.c (hunk 3 above)
Comment (hariharan-devarajan) [reply test/dlopen/test_dlopen.c]: i forgot to commit the final. I meant to define ```_GNU_SOURCE``` instead.

File: src/gotcha_dl.c (hunk 4 above)
Comment (hariharan-devarajan) [reply src/gotcha_dl.c:62]: Ok i looked up the ```prepare_symbol``` code and used the ```lookup_gnu_hash_symbol``` part of code. In here I had to use the correct offset based on is_rela.

File: test/dlopen/test_dlopen.c (hunk 5 above)
Comment (hariharan-devarajan) [reply test/dlopen/test_dlopen.c:106]: I added a second library called libnum2. Where I am now checking the next symbol.

File: src/gotcha_dl.c (hunk 2 above)
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: renamed function to gotchas_dlsym_rtld_next_lookup

File: src/gotcha_dl.c (hunk 8 above)
[the remark this answers is not in the document]
Comment (mplegendre) [reply src/gotcha_dl.c]: Hmm. You're right on the link_map pointer not being there. But name won't quite be unique either. On some older GLIBC versions both the VDSO and the executable have blank name strings. 

I think you could use both name and load-address for uniqueness. I don't recollect any system where they wouldn't be unique when combined.

File: src/gotcha_dl.c (hunk 2 above)
Comment (mplegendre) [reply src/gotcha_dl.c]: We shouldn't have to infinite recurse. This is a wrapped function, and gotcha_get_wrappee() can get you a function pointer to the original_dlsym. By using the original dlsym as much as possible you'll be avoiding a lot of other bugs.

File: src/gotcha_dl.c [hunk 9]
```diff
@@ -5,7 +5,137 @@
...
+    /* Iterative over the library headers and find the caller
+     * the address of the caller is set in addrs->library_laddr
+     **/
+    struct Addrs addrs;
+    addrs.found = 0;
+    addrs.lookup_addr = caller;
+    addrs.lmap = _r_debug.r_map;
+    void* symbol;
+    dl_iterate_phdr(lib_header_callback, &addrs);
+    if (addrs.lmap->l_next) {
```
Comment (mplegendre) [inline src/gotcha_dl.c:111]: Also, this 'if' statement is unnecessary. If addrs.lmap->l_ next is NULL, then the below 'for' loop will just not iterate over anything.

File: src/gotcha_dl.c [hunk 10]
```diff
@@ -5,7 +5,137 @@
...
+        for (lib_iter = addrs.lmap->l_next; lib_iter != 0; lib_iter = lib_iter->l_next) {
+            /* lookup symbol on the next lib or next-to-next lib which has symbol
+             * This selection depends on RTLD_DEFAULT or RTLD_NEXT
+             **/
+            int res = dl_lookup_symbol_x(name, lib_iter, &symbol);
+            if (res != -1) {
+                if (handle == RTLD_DEFAULT) {
+                    return symbol;
+                } else if (found_sym && handle == RTLD_NEXT){
+                    return symbol;
```
Comment (mplegendre) [inline src/gotcha_dl.c:122]: Rather than return the symbol, we should return the link_map that contains the symbol. Also see the below comment on what to do with that link_map.

File: src/gotcha_dl.c [hunk 11]
```diff
@@ -56,12 +186,12 @@ static void* dlsym_wrapper(void* handle, const char* symbol_name){
   debug_printf(1, "User called dlsym(%p, %s)\n", handle, symbol_name);
 
   if(handle == RTLD_NEXT){
-    return _dl_sym(RTLD_NEXT, symbol_name ,__builtin_return_address(0));
+    return gotchas_dlsym_rtld_next_lookup(RTLD_NEXT, symbol_name ,__builtin_return_address(0));
```
Comment (mplegendre) [inline src/gotcha_dl.c:188]: As mentioned above, I suggest having gotchas_dlsym_rtld_next_lookup() return a link_map. We can then use that link_map to make a call like:
```
return orig_dlsym(link_map, symbol_name)
```

That lets GLIBC's dlsym() do the actual symbol resolution, but limits it to the library we identified as the proper RTLD_NEXT.  As mentioned, symbol resolution has a whole bunch of corner cases we don't want to handle.

File: src/gotcha_dl.c [hunk 12]
```diff
@@ -5,7 +5,137 @@
...
+                if (addrs->lookup_addr >= start_addr && addrs->lookup_addr <= end_addr) {
+                    name = info->dlpi_name;
+                    break;
+                }
+            }
+        }
+        if (name) {
+            struct link_map *current = addrs->lmap;
+            while (current) {
+                if (strcmp(current->l_name, name) == 0) {
```
Comment (mplegendre) [inline src/gotcha_dl.c]: Mentioned this in comments before I started a review, but we should probably do both a name and a base_address comparison to find the match.

File: src/gotcha_dl.c (hunk 2 above)
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: I agree now. I checked it and it works. So I changed the code to just do custom lookup for RTLD_NEXT.

File: src/gotcha_dl.c (hunk 8 above)
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: Ok i added load_address which i am thinking is the base address which is info->dlpi_addr. As I understand that this can be 0 in which case we check the name.

File: src/gotcha_dl.c [hunk 13]
```diff
@@ -54,14 +184,9 @@ static void* dlsym_wrapper(void* handle, const char* symbol_name){
...
-
   if(handle == RTLD_NEXT){
-    return _dl_sym(RTLD_NEXT, symbol_name ,__builtin_return_address(0));
+    return gotchas_dlsym_rtld_next_lookup(RTLD_NEXT, symbol_name ,__builtin_return_address(0));
   }
-  if(handle == RTLD_DEFAULT) {
-    return _dl_sym(RTLD_DEFAULT, symbol_name,__builtin_return_address(0));
-  }
-  
   result = lookup_hashtable(&function_hash_table, (hash_key_t) symbol_name, (hash_data_t *) &binding);
```
Comment (mplegendre) [inline src/gotcha_dl.c:190]: Independent from your commit here (since this is in the original code)--I wonder if we should hoist the lookup_hashtable() call and test above the 'if (handle == RTLD_NEXT)' test. As we have this coded now, if the app calls dlsym(RTLD_NEXT, ...) or dlsym(RTLD_DEFAULT, ...) then it can go around gotcha's wrappers. 

I think we should be checking whether we wrap symbol_name, return the wrapper if so, then if not we can fall through into original dlsym behavior.  Not sure why it was originally coded like this.

**Review by mplegendre — CHANGES_REQUESTED** [review]

File: src/gotcha_dl.c [hunk 14]
```diff
@@ -5,7 +5,137 @@
...
+ * We check if the caller's virtual address is between base address and the virtual addr + memory size.
+ *
+ * @param info, information about headers
+ * @param size, size of headers
+ * @param data, data from caller
+ * @return
+ */
+int lib_header_callback(struct dl_phdr_info * info, size_t size, void * data) {
+    struct Addrs* addrs = data;
+    if (!addrs->found) {
```
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: ok fixed.

File: src/gotcha_dl.c [hunk 15]
```diff
@@ -5,7 +5,137 @@
...
+        char *name = NULL;
+        for (int i = 0; i < info->dlpi_phnum; ++i) {
+            if (info->dlpi_phdr[i].p_type == PT_LOAD) {
+                ElfW(Addr) base_addr = info->dlpi_addr;
+                if (info->dlpi_addr == 0) base_addr = info->dlpi_phdr[i].p_offset;
```
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: fixed.

File: src/gotcha_dl.c [hunk 16]
```diff
@@ -5,7 +5,137 @@
...
+                ElfW(Addr) start_addr = base_addr + info->dlpi_phdr[i].p_vaddr;
+                ElfW(Addr) end_addr = start_addr + info->dlpi_phdr[i].p_memsz;
+                if (addrs->lookup_addr >= start_addr && addrs->lookup_addr <= end_addr) {
```
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: fixed.

File: src/gotcha_dl.c [hunk 17]
```diff
@@ -5,7 +5,137 @@
...
+        if (result != -1) {
+            if (GOTCHA_CHECK_VISIBILITY(symtab[result])) {
+                *symbol = (void *) (symtab[result].st_value + lmap->l_addr);
+                return 0;
+            } else {
+                debug_printf(3, "Symbol %s found but not exported in %s\n", name, LIB_NAME(lmap));
+            }
+        } else {
+            debug_printf(3, "%s not found in %s\n", name, LIB_NAME(lmap));
+        }
```
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c:49]: created lookup_exported_symbol() which is called from my code as well as prepare_symbol()

File: src/gotcha_dl.c [hunk 18]
```diff
@@ -5,7 +5,137 @@
...
+ * @return symbol pointer
+ */
+int dl_lookup_symbol_x(const char *name, struct link_map *lmap, void** symbol) {
+    long result;
+    INIT_DYNAMIC(lmap)
+    if (gnu_hash) {
+        debug_printf(3, "Checking GNU hash for %s in %s\n", name, LIB_NAME(lmap));
+        struct gnu_hash_header * header;
+        if (is_rela) header = (struct gnu_hash_header *) (gnu_hash);
+        else header = (struct gnu_hash_header *) (lmap->l_addr + gnu_hash);
```
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: This is removed as i am using lookup_exported_symbol().

File: src/gotcha_dl.c (hunk 9 above)
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: fixed

File: src/gotcha_dl.c (hunk 10 above)
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: returning link map now.

File: src/gotcha_dl.c (hunk 11 above)
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: fixed. Returning the lmap. and then letting original function do the symbol lookup on lmap.

File: src/gotcha_dl.c (hunk 12 above)
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: fixed

File: src/gotcha_dl.c (hunk 13 above)
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: I agree. The logic of first checking wrapper seem more logical. Fixed the logic.

File: src/gotcha_dl.c [hunk 19]
```diff
@@ -5,7 +5,92 @@
...
+ * @param data, data from caller
+ * @return
+ */
+int lib_header_callback(struct dl_phdr_info * info, size_t size, void * data) {
+    struct Addrs* addrs = data;
+    char *name = NULL;
+    ElfW(Addr) load_address;
+    for (int i = 0; i < info->dlpi_phnum; ++i) {
+        if (info->dlpi_phdr[i].p_type == PT_LOAD) {
+            ElfW(Addr) base_addr = info->dlpi_addr + info->dlpi_phdr[i].p_offset;
```
Comment (mplegendre) [inline src/gotcha_dl.c:31]: Still a wrong base_addr calculation. 'base_addr = info->dlpi_addr' is all you need.

p_offset tells you the byte offset of this PHDR in the on-disk library file. It's not part of an in-memory address calculation.

**Review by mplegendre — CHANGES_REQUESTED** [review]
Getting closer.

Though I think some of the remaining bugs should have triggered a test case failure. If you've got passing tests, then I'm unsure of how. I'm going to either find that old test case I had (when I last tried it wasn't where I expected) or rewrite it and try it out before we merge.

File: src/gotcha_dl.c [hunk 20]
```diff
@@ -5,7 +5,92 @@
...
+    /* Iterative over the library headers and find the caller
+     * the address of the caller is set in addrs->library_laddr
+     **/
+    struct Addrs addrs;
+    addrs.lookup_addr = caller;
+    addrs.lmap = _r_debug.r_map;
+    void* symbol;
+    dl_iterate_phdr(lib_header_callback, &addrs);
+    int found_sym = 0;
+    struct link_map *handle = addrs.lmap->l_next;
```
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c:75]: So your saying if our addrs.lmap is already NULL then we should throw an error.

[the remark this answers is not in the document]
Comment (mplegendre) [reply src/gotcha_dl.c:75]: I'm saying that we need to note when we don't find a match for 'who' and then return an error--whatever the mechanism. You could use addrs.lmap to communicate that. Except as the code is now addrs.lmap is initialized to _r_debug.r_map, so it won't ever be NULL.

(Also, it later occurred to me how tests are passing. The wrong base address calculation bug meant we'd never match a library for 'who'. But this bug means we'll still search for a symbol even when there's no match. So two bugs are canceling each other well enough to pass a test.)

[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c:75]:
```
if (addrs.lmap == NULL) {
        error_printf("RTLD_NEXT used in code not dynamically loaded");
        exit (127);
    }
```

File: src/gotcha_dl.c (hunk 19 above)
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: fixed

File: src/gotcha_dl.c [hunk 21]
```diff
@@ -5,7 +5,92 @@
...
+    while(handle) {
+        /* lookup symbol on the next-to-next lib which has symbol
+         * for RTLD_NEXT
+         **/
+        long result = lookup_exported_symbol(name, handle, &symbol);
+        if (result != -1) {
+            if (found_sym){
```
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c]: I had that before our talk. Somehow I misunderstood.

File: src/gotcha_dl.c (hunk 20 above)
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c:78]: When u say "find a match for who". What I understand is that, we have lookup the address of "who" and that could not be matched from my _r_debug. Another interpretation I can think of is, there is some internal structure that we are not able to use which could return NULL based on scope.

[the remark this answers is not in the document]
Comment (mplegendre) [reply src/gotcha_dl.c:78]: I'm referring to the first case. We have the lookup address, and no library contains that address.

This could happen if JIT code calls dlsym(RTLD_NEXT, ...).

[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c:81]: Ok in that case all i have to do is add a int found flag which will be set to one only when the lib is found. Otherwise it will remain 0 as initially set.

[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c:81]: I will throw an error if caller was not found.

[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c:81]: fixed.

[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c:81]: BTW, the address calculation was getting matched before. Even with the incorrect code :). Just that the lookup later was passing as well. I checked this based on debug.

[the remark this answers is not in the document]
Comment (mplegendre) [reply src/gotcha_dl.c:81]: Must have been with for segments with '0' offset, which is common but not guaranteed.

File: src/gotcha.c [hunk 22]
```diff
@@ -47,6 +47,48 @@ static void setInternalBindingAddressPointer(void** in, void* value){
...
+    debug_printf(2, "Searching for exported symbols in %s\n", LIB_NAME(lib));
+    INIT_DYNAMIC(lib);
+
+    if (!gnu_hash && !elf_hash) {
+        debug_printf(3, "Library %s does not export or import symbols\n", LIB_NAME(lib));
+        return -1;
+    }
+    result = -1;
+    if (gnu_hash) {
+        debug_printf(3, "Checking GNU hash for %s in %s\n", name);
```
Comment (mplegendre) [inline src/gotcha.c:66]: Also, this printf is missing a parameter

File: src/gotcha_dl.c (hunk 20 above)
[the remark this answers is not in the document]
Comment (hariharan-devarajan) [reply src/gotcha_dl.c:81]: Yes i checked that was the case for me :).

File: src/gotcha.c (hunk 22 above)
Comment (hariharan-devarajan) [reply src/gotcha.c]: fixed.

**Comment by hariharan-devarajan** [comment]
> I'm going to give you a stand-alone test case on quartz. If we can get that passing (and preferably integrated into gotcha's tests) then I think we'll be good.
> 
> Except... When I run the test case on quartz everything's starting to look good. But when I run it on Ubuntu on my laptop the test fails because dlsym(RTLD_NEXT, ...) incorrectly returns NULL, even without gotcha. I'm not sure what's going on there--I've heard about some buggy RTLD_NEXT implementations floating around. Maybe my laptop is one.
> 
> Which then begs the question, do we try to match original behavior on a buggy RTLD_NEXT implementation? Or do we provide the corrected behavior?
> 
> I'm thinking we should always provide the corrected behavior. But we'll need to adapt my test case to that.

I am running on the latest ubuntu and the test cases pass for me. Which test case fails for u?

**Comment by hariharan-devarajan** [comment]
> I'm going to give you a stand-alone test case on quartz. If we can get that passing (and preferably integrated into gotcha's tests) then I think we'll be good.
> 
> Except... When I run the test case on quartz everything's starting to look good. But when I run it on Ubuntu on my laptop the test fails because dlsym(RTLD_NEXT, ...) incorrectly returns NULL, even without gotcha. I'm not sure what's going on there--I've heard about some buggy RTLD_NEXT implementations floating around. Maybe my laptop is one.
> 
> Which then begs the question, do we try to match original behavior on a buggy RTLD_NEXT implementation? Or do we provide the corrected behavior?
> 
> I'm thinking we should always provide the corrected behavior. But we'll need to adapt my test case to that.

Do u want add CI tests in github actions trying different versions of ubuntu to see which cases would pass and where it might fail? 

My guess is glibc might have some changes along the way where some functionality diverged along the way. It would be good document those cases.

**Comment by hariharan-devarajan** [comment]
@mplegendre I was looking at various glibc versions per ubuntu distro.


22.04 LTS Jammy glibc 2.35
20.04 LTS focal glibc 2.31
18.04 LTS bionic glibc: 2.27
16.04 LTS xenial glibc: 2.23

Which one does your belong to?

**Comment by mplegendre** [comment]
My ubuntu is 22.04, also with glibc 2.35. Not sure why it's testing different then.

CI testing for this project would be great. But I don't think it has to happen with this commit. We could work that separately. Let me take a (hopefully) last look over everything.

File: test/dlopen/test_dlopen.c [hunk 23]
```diff
@@ -68,6 +73,11 @@ int main()
       fprintf(stderr, "ERROR: Test failed to dlopen libnum.so\n");
       return -1;
    }
+    libnum = dlopen(LIB2_NAME, RTLD_NOW);
```
Comment (bertwesarg) [inline test/dlopen/test_dlopen.c:76]: this overwrites `libnum` from line 71, where it holds the handle to `libnum.so`, and hence all tests are now carried out on `libnum2.so`. was this intended?

Comment (hariharan-devarajan) [reply test/dlopen/test_dlopen.c:76]: Yes the reason was that we wanted to test the NEXT and default test case in dlsym.
